channels:
- conda-forge
dependencies:
- python=3.10.12
- pip<=23.0.1
- pip:
  - mlflow==2.9.2
  - cloudpickle==3.1.1
  - numpy==1.26.2
  - packaging==23.2
  - psutil==7.0.0
  - pyyaml==6.0.2
  - scikit-learn==1.3.2
  - scipy==1.15.2
name: mlflow-env
